### ISSUE TITLE
交流探讨。

### ISSUE THREAD

**Issue by Adenialzz** [junyussh/iqiyi-anime-recognition#1]
请问是做检测还是识别，有思路吗，可以交流一下吗？

**Comment by junyussh** [comment]
我目前打算先做識別，還比較菜，可能先照著[這個範例](https://www.paddlepaddle.org.cn/documentation/docs/en/tutorial/cv_case/image_search/image_search.html)改改看。

**Comment by Adenialzz** [comment]
好。加油，期待你的结果。
